Branch 2
gri6ri/go_final_project pull request #1
Opened 2024-04-28 21:24 UTC by Gri6ri

Реализован базовый функционал планировщика задач

2024-04-29 13:11 UTC, robotomize requested changes
Привет, пока детально не смотрел, но ситнтаксис файлов должен быть андескор в go  то есть post_rule.go и тд. 
Проект работает в 80% случаях. Не работает создание периодической задачи еженедельно, и по месяцам. У вас отдается 400. Нужно проверить и пофиксить функционал, после этого продолжим ревью

2024-05-02 09:52 UTC, Gri6ri commented
> Привет, пока детально не смотрел, но ситнтаксис файлов должен быть андескор в go то есть post_rule.go и тд. Проект работает в 80% случаях. Не работает создание периодической задачи еженедельно, и по месяцам. У вас отдается 400. Нужно проверить и пофиксить функционал, после этого продолжим ревью

Привет! Я реализовал только базовый функционал. Обработка недель и месяцов - это [задание со звездочкой](https://practicum.yandex.ru/learn/go-developer-basic/courses/47aa0a67-f24c-4020-ac3c-1ccc614af70b/sprints/289693/topics/c7326e45-3d94-40d4-95a0-3517086a1a49/lessons/dc6f9af9-34a8-437e-92c7-f6aacf00160d/)

2024-05-02 19:04 UTC, robotomize requested changes
Еще обратной связи оставил. Обязательно исправьте нейминг, get_tasks_rule.go task_rules вообщем андескор в нейминге файлов должен быть.  Обратите внимание на комменты, не разрывайте структуру и методы, группируйте согласно слоям, работа с баой данных -> store. Обработчики в handler.go например вместе со структурой Handler. Вообщем поправьте эти вещи, нейминг файлов и будем двигаться к завершению

2024-05-02 19:04 UTC, robotomize commented on scheduler.go
> +package main
Наименование этого файла абсолютно не коррелирует с тем, что в нем происходит=)

2024-05-02 19:04 UTC, robotomize commented on scheduler.go
> +package main
db.go, setup.go

2024-05-02 19:04 UTC, robotomize commented on structFuncEtc.go
> +type Store struct {
Лучше Store унести в отдельный файл или вообще пакет и группировать по файлам скорее все что связано с DB и Store это отдельный файл или пакет, все что с хэндлерами отдельный скажем handler это было бы нагляднее.

Плюс лучше структуру и ее методы по файлам лишний раз не разрывать.

2024-05-02 19:04 UTC, robotomize commented on repeatRule.go
> +	if firstPart == "y" {
Лучше switch {

case firstPart == "y":
case  firstPart == "d" && len(repeatParts) == 2:
default:

}

Мне кажется

2024-05-02 19:04 UTC, robotomize commented on structFuncEtc.go
> +type Store struct {
Сделайте лучше файл models и туда поместите Task NewStore и Store в store.go. Методы работы со стором тоже туда

2024-05-03 11:23 UTC, robotomize approved these changes
Моменты поправлены, сам сервис работает, оки, принято! Успехов в дальнейшем обучении!

2024-05-03 11:23 UTC, robotomize commented on handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Тут лучше наверное залогировать, статус попробовтаь отдать, но не факт что получится

2024-07-25 08:59 UTC, merged